"""init

Revision ID: 172603535517
Revises: 
Create Date: 2024-04-25 17:34:05.031125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172603535517'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gizi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=False),
    sa.Column('born_weight', sa.Double(), nullable=False),
    sa.Column('born_height', sa.Double(), nullable=False),
    sa.Column('weight', sa.Double(), nullable=False),
    sa.Column('height', sa.Double(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gizi')
    # ### end Alembic commands ###
